
export type Topic = {
  key: string;
  emoji: string;
  words: {
    en: string[];
    es: string[];
    fr: string[];
    it: string[];
  };
};

export const topics: Topic[] = [
  {
    key: 'fruits',
    emoji: '🍎',
    words: {
      en: ['Apple', 'Banana', 'Orange', 'Grape', 'Strawberry', 'Blueberry', 'Raspberry', 'Blackberry', 'Mango', 'Pineapple', 'Watermelon', 'Melon', 'Peach', 'Plum', 'Pear', 'Cherry', 'Kiwi', 'Lemon', 'Lime', 'Coconut', 'Papaya', 'Guava', 'Fig', 'Date', 'Apricot', 'Nectarine', 'Pomegranate', 'Cranberry', 'Passion Fruit', 'Lychee', 'Grapefruit', 'Mandarin', 'Tangerine', 'Cantaloupe', 'Honeydew', 'Avocado', 'Tomato', 'Olive', 'Starfruit', 'Dragon Fruit', 'Persimmon', 'Mulberry', 'Jackfruit', 'Plantain', 'Quince', 'Currant', 'Soursop', 'Uva', 'Raisin'],
      es: ['Manzana', 'Banana', 'Naranja', 'Uva', 'Fresa', 'Arándano', 'Frambuesa', 'Mora', 'Mango', 'Piña', 'Sandía', 'Melón', 'Durazno', 'Ciruela', 'Pera', 'Cereza', 'Kiwi', 'Limón', 'Lima', 'Coco', 'Papaya', 'Guayaba', 'Higo', 'Dátil', 'Albaricoque', 'Nectarina', 'Granada', 'Arándano Rojo', 'Maracuyá', 'Lichi', 'Pomelo', 'Mandarina', 'Tangerina', 'Cantalupo', 'Melón Verde', 'Aguacate', 'Tomate', 'Aceituna', 'Carambola', 'Pitahaya', 'Caqui', 'Mora', 'Yaca', 'Plátano', 'Membrillo', 'Grosella', 'Guanábana', 'Uva', 'Pasa'],
      fr: ['Pomme', 'Banane', 'Orange', 'Raisin', 'Fraise', 'Myrtille', 'Framboise', 'Mûre', 'Mangue', 'Ananas', 'Pastèque', 'Melon', 'Pêche', 'Prune', 'Poire', 'Cerise', 'Kiwi', 'Citron', 'Citron Vert', 'Noix de Coco', 'Papaye', 'Goyave', 'Figue', 'Datte', 'Abricot', 'Nectarine', 'Grenade', 'Canneberge', 'Fruit de la Passion', 'Litchi', 'Pamplemousse', 'Mandarine', 'Tangerine', 'Cantaloup', 'Melon Miel', 'Avocat', 'Tomate', 'Olive', 'Carambole', 'Fruit du Dragon', 'Kaki', 'Mûre', 'Jacquier', 'Plantain', 'Coing', 'Groseille', 'Corossol', 'Raisin', 'Raisin Sec'],
      it: ['Mela', 'Banana', 'Arancia', 'Uva', 'Fragola', 'Mirtillo', 'Lampone', 'Mora', 'Mango', 'Ananas', 'Anguria', 'Melone', 'Pesca', 'Prugna', 'Pera', 'Ciliegia', 'Kiwi', 'Limone', 'Lime', 'Cocco', 'Papaya', 'Guava', 'Fico', 'Dattero', 'Albicocca', 'Nettarina', 'Melograno', 'Mirtillo Rosso', 'Frutto della Passione', 'Litchi', 'Pompelmo', 'Mandarino', 'Tangerino', 'Cantalupo', 'Melone Giallo', 'Avocado', 'Pomodoro', 'Oliva', 'Carambola', 'Frutto del Drago', 'Cachi', 'Gelso', 'Giaca', 'Platano', 'Mela Cotogna', 'Ribes', 'Guanabana', 'Uva', 'Uvetta'],
    },
  },
  {
    key: 'animals',
    emoji: '🐘',
    words: {
      en: ['Lion', 'Tiger', 'Elephant', 'Giraffe', 'Zebra', 'Monkey', 'Bear', 'Penguin', 'Kangaroo', 'Koala', 'Panda', 'Dog', 'Cat', 'Horse', 'Cow', 'Pig', 'Sheep', 'Goat', 'Chicken', 'Duck', 'Eagle', 'Owl', 'Parrot', 'Dolphin', 'Whale', 'Shark', 'Octopus', 'Frog', 'Snake', 'Lizard', 'Crocodile', 'Alligator', 'Wolf', 'Fox', 'Deer', 'Rabbit', 'Squirrel', 'Mouse', 'Rat', 'Bat', 'Camel', 'Donkey', 'Leopard', 'Cheetah', 'Hippo', 'Rhino', 'Seal', 'Sea Lion', 'Turtle', 'Crab', 'Lobster'],
      es: ['León', 'Tigre', 'Elefante', 'Jirafa', 'Cebra', 'Mono', 'Oso', 'Pingüino', 'Canguro', 'Koala', 'Panda', 'Perro', 'Gato', 'Caballo', 'Vaca', 'Cerdo', 'Oveja', 'Cabra', 'Pollo', 'Pato', 'Águila', 'Búho', 'Loro', 'Delfín', 'Ballena', 'Tiburón', 'Pulpo', 'Rana', 'Serpiente', 'Lagarto', 'Cocodrilo', 'Caimán', 'Lobo', 'Zorro', 'Ciervo', 'Conejo', 'Ardilla', 'Ratón', 'Rata', 'Murciélago', 'Camello', 'Burro', 'Leopardo', 'Guepardo', 'Hipopótamo', 'Rinoceronte', 'Foca', 'León Marino', 'Tortuga', 'Cangrejo', 'Langosta'],
      fr: ['Lion', 'Tigre', 'Éléphant', 'Girafe', 'Zèbre', 'Singe', 'Ours', 'Pingouin', 'Kangourou', 'Koala', 'Panda', 'Chien', 'Chat', 'Cheval', 'Vache', 'Cochon', 'Mouton', 'Chèvre', 'Poulet', 'Canard', 'Aigle', 'Hibou', 'Perroquet', 'Dauphin', 'Baleine', 'Requin', 'Poulpe', 'Grenouille', 'Serpent', 'Lézard', 'Crocodile', 'Alligator', 'Loup', 'Renard', 'Cerf', 'Lapin', 'Écureuil', 'Souris', 'Rat', 'Chauve-souris', 'Chameau', 'Âne', 'Léopard', 'Guépard', 'Hippopotame', 'Rhinocéros', 'Phoque', 'Otarie', 'Tortue', 'Crabe', 'Homard'],
      it: ['Leone', 'Tigre', 'Elefante', 'Giraffa', 'Zebra', 'Scimmia', 'Orso', 'Pinguino', 'Canguro', 'Koala', 'Panda', 'Cane', 'Gatto', 'Cavallo', 'Mucca', 'Maiale', 'Pecora', 'Capra', 'Pollo', 'Anatra', 'Aquila', 'Gufo', 'Pappagallo', 'Delfino', 'Balena', 'Squalo', 'Polpo', 'Rana', 'Serpente', 'Lucertola', 'Coccodrillo', 'Alligatore', 'Lupo', 'Volpe', 'Cervo', 'Coniglio', 'Scoiattolo', 'Topo', 'Ratto', 'Pipistrello', 'Cammello', 'Asino', 'Leopardo', 'Ghepardo', 'Ippopotamo', 'Rinoceronte', 'Foca', 'Leone Marino', 'Tartaruga', 'Granchio', 'Aragosta'],
    },
  },
  {
    key: 'countries',
    emoji: '🌍',
    words: {
      en: ['USA', 'Canada', 'Mexico', 'Brazil', 'Argentina', 'Chile', 'Peru', 'Colombia', 'Spain', 'France', 'Germany', 'Italy', 'Portugal', 'United Kingdom', 'Ireland', 'Netherlands', 'Belgium', 'Switzerland', 'Austria', 'Sweden', 'Norway', 'Denmark', 'Finland', 'Poland', 'Czech Republic', 'Greece', 'Turkey', 'Russia', 'Ukraine', 'China', 'Japan', 'South Korea', 'India', 'Pakistan', 'Thailand', 'Vietnam', 'Philippines', 'Indonesia', 'Australia', 'New Zealand', 'Egypt', 'Morocco', 'South Africa', 'Nigeria', 'Kenya', 'Israel', 'Saudi Arabia', 'UAE', 'Iran'],
      es: ['EE.UU.', 'Canadá', 'México', 'Brasil', 'Argentina', 'Chile', 'Perú', 'Colombia', 'España', 'Francia', 'Alemania', 'Italia', 'Portugal', 'Reino Unido', 'Irlanda', 'Países Bajos', 'Bélgica', 'Suiza', 'Austria', 'Suecia', 'Noruega', 'Dinamarca', 'Finlandia', 'Polonia', 'República Checa', 'Grecia', 'Turquía', 'Rusia', 'Ucrania', 'China', 'Japón', 'Corea del Sur', 'India', 'Pakistán', 'Tailandia', 'Vietnam', 'Filipinas', 'Indonesia', 'Australia', 'Nueva Zelanda', 'Egipto', 'Marruecos', 'Sudáfrica', 'Nigeria', 'Kenia', 'Israel', 'Arabia Saudita', 'EAU', 'Irán'],
      fr: ['États-Unis', 'Canada', 'Mexique', 'Brésil', 'Argentine', 'Chili', 'Pérou', 'Colombie', 'Espagne', 'France', 'Allemagne', 'Italie', 'Portugal', 'Royaume-Uni', 'Irlande', 'Pays-Bas', 'Belgique', 'Suisse', 'Autriche', 'Suède', 'Norvège', 'Danemark', 'Finlande', 'Pologne', 'République Tchèque', 'Grèce', 'Turquie', 'Russie', 'Ukraine', 'Chine', 'Japon', 'Corée du Sud', 'Inde', 'Pakistan', 'Thaïlande', 'Vietnam', 'Philippines', 'Indonésie', 'Australie', 'Nouvelle-Zélande', 'Égypte', 'Maroc', 'Afrique du Sud', 'Nigéria', 'Kenya', 'Israël', 'Arabie Saoudite', 'EAU', 'Iran'],
      it: ['Stati Uniti', 'Canada', 'Messico', 'Brasile', 'Argentina', 'Cile', 'Perù', 'Colombia', 'Spagna', 'Francia', 'Germania', 'Italia', 'Portogallo', 'Regno Unito', 'Irlanda', 'Paesi Bassi', 'Belgio', 'Svizzera', 'Austria', 'Svezia', 'Norvegia', 'Danimarca', 'Finlandia', 'Polonia', 'Repubblica Ceca', 'Grecia', 'Turchia', 'Russia', 'Ucraina', 'Cina', 'Giappone', 'Corea del Sud', 'India', 'Pakistan', 'Tailandia', 'Vietnam', 'Filippine', 'Indonesia', 'Australia', 'Nuova Zelanda', 'Egitto', 'Marocco', 'Sudafrica', 'Nigeria', 'Kenya', 'Israele', 'Arabia Saudita', 'EAU', 'Iran'],
    },
  },
  {
    key: 'sports',
    emoji: '⚽',
    words: {
      en: ['Soccer', 'Basketball', 'Tennis', 'Baseball', 'Volleyball', 'Swimming', 'Running', 'Cycling', 'Boxing', 'MMA', 'Wrestling', 'Golf', 'Hockey', 'Ice Hockey', 'Field Hockey', 'Rugby', 'Cricket', 'American Football', 'Handball', 'Table Tennis', 'Badminton', 'Skateboarding', 'Surfing', 'Snowboarding', 'Skiing', 'Gymnastics', 'Athletics', 'Weightlifting', 'CrossFit', 'Karate', 'Judo', 'Taekwondo', 'Fencing', 'Archery', 'Rowing', 'Canoeing', 'Kayaking', 'Triathlon', 'Climbing', 'Parkour', 'Motorsport', 'Formula 1', 'MotoGP', 'Rally', 'BMX', 'Diving', 'Water Polo'],
      es: ['Fútbol', 'Baloncesto', 'Tenis', 'Béisbol', 'Voleibol', 'Natación', 'Correr', 'Ciclismo', 'Boxeo', 'MMA', 'Lucha', 'Golf', 'Hockey', 'Hockey sobre Hielo', 'Hockey sobre Hierba', 'Rugby', 'Críquet', 'Fútbol Americano', 'Balonmano', 'Tenis de Mesa', 'Bádminton', 'Skate', 'Surf', 'Snowboard', 'Esquí', 'Gimnasia', 'Atletismo', 'Halterofilia', 'CrossFit', 'Karate', 'Judo', 'Taekwondo', 'Esgrima', 'Tiro con Arco', 'Remo', 'Piragüismo', 'Kayak', 'Triatlón', 'Escalada', 'Parkour', 'Automovilismo', 'Fórmula 1', 'MotoGP', 'Rally', 'BMX', 'Clavados', 'Waterpolo'],
      fr: ['Football', 'Basket-ball', 'Tennis', 'Baseball', 'Volley-ball', 'Natation', 'Course', 'Cyclisme', 'Boxe', 'MMA', 'Lutte', 'Golf', 'Hockey', 'Hockey sur Glace', 'Hockey sur Gazon', 'Rugby', 'Cricket', 'Football Américain', 'Handball', 'Tennis de Table', 'Badminton', 'Skateboard', 'Surf', 'Snowboard', 'Ski', 'Gymnastique', 'Athlétisme', 'Haltérophilie', 'CrossFit', 'Karaté', 'Judo', 'Taekwondo', 'Escrime', 'Tir à l arc', 'Aviron', 'Canoë', 'Kayak', 'Triathlon', 'Escalade', 'Parkour', 'Sport Automobile', 'Formule 1', 'MotoGP', 'Rallye', 'BMX', 'Plongeon', 'Water-polo'],
      it: ['Calcio', 'Pallacanestro', 'Tennis', 'Baseball', 'Pallavolo', 'Nuoto', 'Corsa', 'Ciclismo', 'Pugilato', 'MMA', 'Lotta', 'Golf', 'Hockey', 'Hockey su Ghiaccio', 'Hockey su Prato', 'Rugby', 'Cricket', 'Football Americano', 'Pallamano', 'Tennistavolo', 'Badminton', 'Skateboard', 'Surf', 'Snowboard', 'Sci', 'Ginnastica', 'Atletica', 'Sollevamento Pesi', 'CrossFit', 'Karate', 'Judo', 'Taekwondo', 'Scherma', 'Tiro con l arco', 'Canottaggio', 'Canoa', 'Kayak', 'Triathlon', 'Arrampicata', 'Parkour', 'Sport Motoristici', 'Formula 1', 'MotoGP', 'Rally', 'BMX', 'Tuffi', 'Pallanuoto'],
    },
  },
  {
    key: 'professions',
    emoji: '🧑‍🏫',
    words: {
      en: ['Doctor', 'Nurse', 'Teacher', 'Professor', 'Engineer', 'Programmer', 'Developer', 'Designer', 'Artist', 'Painter', 'Musician', 'Singer', 'Actor', 'Actress', 'Director', 'Producer', 'Writer', 'Journalist', 'Photographer', 'Chef', 'Cook', 'Baker', 'Waiter', 'Bartender', 'Pilot', 'Flight Attendant', 'Scientist', 'Researcher', 'Firefighter', 'Police Officer', 'Detective', 'Lawyer', 'Judge', 'Accountant', 'Economist', 'Architect', 'Builder', 'Electrician', 'Plumber', 'Mechanic', 'Technician', 'Carpenter', 'Farmer', 'Gardener', 'Veterinarian', 'Dentist', 'Pharmacist', 'Psychologist'],
      es: ['Médico', 'Enfermero', 'Maestro', 'Profesor', 'Ingeniero', 'Programador', 'Desarrollador', 'Diseñador', 'Artista', 'Pintor', 'Músico', 'Cantante', 'Actor', 'Actriz', 'Director', 'Productor', 'Escritor', 'Periodista', 'Fotógrafo', 'Chef', 'Cocinero', 'Panadero', 'Camarero', 'Barman', 'Piloto', 'Azafata', 'Científico', 'Investigador', 'Bombero', 'Policía', 'Detective', 'Abogado', 'Juez', 'Contador', 'Economista', 'Arquitecto', 'Constructor', 'Electricista', 'Fontanero', 'Mecánico', 'Técnico', 'Carpintero', 'Granjero', 'Jardinero', 'Veterinario', 'Dentista', 'Farmacéutico', 'Psicólogo'],
      fr: ['Médecin', 'Infirmier', 'Enseignant', 'Professeur', 'Ingénieur', 'Programmeur', 'Développeur', 'Designer', 'Artiste', 'Peintre', 'Musicien', 'Chanteur', 'Acteur', 'Actrice', 'Réalisateur', 'Producteur', 'Écrivain', 'Journaliste', 'Photographe', 'Chef', 'Cuisinier', 'Boulanger', 'Serveur', 'Barman', 'Pilote', 'Hôtesse de l air', 'Scientifique', 'Chercheur', 'Pompier', 'Policier', 'Détective', 'Avocat', 'Juge', 'Comptable', 'Économiste', 'Architecte', 'Constructeur', 'Électricien', 'Plombier', 'Mécanicien', 'Technicien', 'Charpentier', 'Agriculteur', 'Jardinier', 'Vétérinaire', 'Dentiste', 'Pharmacien', 'Psychologue'],
      it: ['Dottore', 'Infermiere', 'Insegnante', 'Professore', 'Ingegnere', 'Programmatore', 'Sviluppatore', 'Designer', 'Artista', 'Pittore', 'Musicista', 'Cantante', 'Attore', 'Attrice', 'Regista', 'Produttore', 'Scrittore', 'Giornalista', 'Fotografo', 'Chef', 'Cuoco', 'Panettiere', 'Cameriere', 'Barista', 'Pilota', 'Assistente di Volo', 'Scienziato', 'Ricercatore', 'Vigile del Fuoco', 'Poliziotto', 'Detective', 'Avvocato', 'Giudice', 'Commercialista', 'Economista', 'Architetto', 'Costruttore', 'Elettricista', 'Idraulico', 'Meccanico', 'Tecnico', 'Falegname', 'Contadino', 'Giardiniere', 'Veterinario', 'Dentista', 'Farmacista', 'Psicologo'],
    },
  },
  {
    key: 'kitchen items',
    emoji: '🔪',
    words: {
      en: ['Spoon', 'Fork', 'Knife', 'Plate', 'Bowl', 'Cup', 'Mug', 'Glass', 'Pan', 'Pot', 'Frying Pan', 'Saucepan', 'Oven', 'Microwave', 'Toaster', 'Blender', 'Mixer', 'Kettle', 'Coffee Maker', 'Teapot', 'Cutting Board', 'Spatula', 'Ladle', 'Whisk', 'Peeler', 'Grater', 'Colander', 'Strainer', 'Rolling Pin', 'Measuring Cup', 'Measuring Spoon', 'Can Opener', 'Bottle Opener', 'Tongs', 'Napkin', 'Paper Towel', 'Aluminum Foil', 'Plastic Wrap', 'Dishwasher', 'Sink', 'Fridge', 'Freezer', 'Trash Can', 'Salt', 'Pepper', 'Sugar', 'Oil'],
      es: ['Cuchara', 'Tenedor', 'Cuchillo', 'Plato', 'Cuenco', 'Taza', 'Tazón', 'Vaso', 'Sartén', 'Olla', 'Sartén', 'Cacerola', 'Horno', 'Microondas', 'Tostadora', 'Licuadora', 'Batidora', 'Hervidor', 'Cafetera', 'Tetera', 'Tabla de Cortar', 'Espátula', 'Cucharón', 'Batidor', 'Pelador', 'Rallador', 'Colador', 'Colador', 'Rodillo', 'Taza Medidora', 'Cuchara Medidora', 'Abrelatas', 'Abrebotellas', 'Pinzas', 'Servilleta', 'Toalla de Papel', 'Papel de Aluminio', 'Film Transparente', 'Lavavajillas', 'Fregadero', 'Nevera', 'Congelador', 'Basura', 'Sal', 'Pimienta', 'Azúcar', 'Aceite'],
      fr: ['Cuillère', 'Fourchette', 'Couteau', 'Assiette', 'Bol', 'Tasse', 'Mug', 'Verre', 'Poêle', 'Casserole', 'Poêle à frire', 'Casserole', 'Four', 'Micro-ondes', 'Grille-pain', 'Mixeur', 'Batteur', 'Bouilloire', 'Cafetière', 'Théière', 'Planche à Découper', 'Spatule', 'Louche', 'Fouet', 'Éplucheur', 'Râpe', 'Passoire', 'Passoire', 'Rouleau à Pâtisserie', 'Tasse à Mesurer', 'Cuillère à Mesurer', 'Ouvre-boîte', 'Décapsuleur', 'Pince', 'Serviette', 'Essuie-tout', 'Papier Aluminium', 'Film Plastique', 'Lave-vaisselle', 'Évier', 'Réfrigérateur', 'Congélateur', 'Poubelle', 'Sel', 'Poivre', 'Sucre', 'Huile'],
      it: ['Cucchiaio', 'Forchetta', 'Coltello', 'Piatto', 'Ciotola', 'Tazza', 'Tazza', 'Bicchiere', 'Padella', 'Pentola', 'Padella', 'Casseruola', 'Forno', 'Microonde', 'Tostapane', 'Frullatore', 'Sbattitore', 'Bollitore', 'Macchina da Caffè', 'Teiera', 'Tagliere', 'Spatola', 'Mestolo', 'Frusta', 'Pelapatate', 'Grattugia', 'Scolapasta', 'Colino', 'Mattarello', 'Misurino', 'Cucchiaio Dosatore', 'Apriscatole', 'Apribottiglie', 'Pinze', 'Tovagliolo', 'Carta Assorbente', 'Carta Stagnola', 'Pellicola Trasparente', 'Lavastoviglie', 'Lavello', 'Frigorifero', 'Congelatore', 'Pattumiera', 'Sale', 'Pepe', 'Zucchero', 'Olio'],
    },
  },
  {
    key: 'anime and manga',
    emoji: '🍥',
    words: {
      en: ['Naruto', 'Dragon Ball', 'One Piece', 'Attack on Titan', 'My Hero Academia', 'Death Note', 'Fullmetal Alchemist', 'Demon Slayer', 'Jujutsu Kaisen', 'Bleach', 'One Punch Man', 'Tokyo Ghoul', 'Hunter x Hunter', 'Fairy Tail', 'Black Clover', 'Chainsaw Man', 'Spy x Family', 'Pokemon', 'Digimon', 'Yu-Gi-Oh', 'Sailor Moon', 'Dragon Ball Z', 'Boruto', 'Naruto Shippuden', 'JoJo\'s Bizarre Adventure', 'Neon Genesis Evangelion', 'Cowboy Bebop', 'Sword Art Online', 'Blue Lock', 'Haikyuu', 'Tokyo Revengers', 'Dr. Stone', 'Vinland Saga', 'Death Parade', 'Akira', 'Your Name', 'Weathering With You'],
      es: ['Naruto', 'Dragon Ball', 'One Piece', 'Ataque a los Titanes', 'My Hero Academia', 'Death Note', 'Fullmetal Alchemist', 'Kimetsu no Yaiba', 'Jujutsu Kaisen', 'Bleach', 'One Punch Man', 'Tokyo Ghoul', 'Hunter x Hunter', 'Fairy Tail', 'Black Clover', 'Chainsaw Man', 'Spy x Family', 'Pokemon', 'Digimon', 'Yu-Gi-Oh', 'Sailor Moon', 'Dragon Ball Z', 'Boruto', 'Naruto Shippuden', 'JoJo\'s Bizarre Adventure', 'Neon Genesis Evangelion', 'Cowboy Bebop', 'Sword Art Online', 'Blue Lock', 'Haikyuu', 'Tokyo Revengers', 'Dr. Stone', 'Vinland Saga', 'Death Parade', 'Akira', 'Your Name', 'El Tiempo Contigo'],
      fr: ['Naruto', 'Dragon Ball', 'One Piece', 'L\'Attaque des Titans', 'My Hero Academia', 'Death Note', 'Fullmetal Alchemist', 'Demon Slayer', 'Jujutsu Kaisen', 'Bleach', 'One Punch Man', 'Tokyo Ghoul', 'Hunter x Hunter', 'Fairy Tail', 'Black Clover', 'Chainsaw Man', 'Spy x Family', 'Pokemon', 'Digimon', 'Yu-Gi-Oh', 'Sailor Moon', 'Dragon Ball Z', 'Boruto', 'Naruto Shippuden', 'JoJo\'s Bizarre Adventure', 'Neon Genesis Evangelion', 'Cowboy Bebop', 'Sword Art Online', 'Blue Lock', 'Haikyuu', 'Tokyo Revengers', 'Dr. Stone', 'Vinland Saga', 'Death Parade', 'Akira', 'Your Name', 'Les Enfants du Temps'],
      it: ['Naruto', 'Dragon Ball', 'One Piece', 'L\'attacco dei Giganti', 'My Hero Academia', 'Death Note', 'Fullmetal Alchemist', 'Demon Slayer', 'Jujutsu Kaisen', 'Bleach', 'One Punch Man', 'Tokyo Ghoul', 'Hunter x Hunter', 'Fairy Tail', 'Black Clover', 'Chainsaw Man', 'Spy x Family', 'Pokemon', 'Digimon', 'Yu-Gi-Oh', 'Sailor Moon', 'Dragon Ball Z', 'Boruto', 'Naruto Shippuden', 'Le bizzarre avventure di JoJo', 'Neon Genesis Evangelion', 'Cowboy Bebop', 'Sword Art Online', 'Blue Lock', 'Haikyuu', 'Tokyo Revengers', 'Dr. Stone', 'Vinland Saga', 'Death Parade', 'Akira', 'Your Name', 'Weathering with You'],
    },
  },
  {
    key: 'movies',
    emoji: '🎬',
    words: {
      en: ['Titanic', 'Avatar', 'The Matrix', 'Pulp Fiction', 'Forrest Gump', 'The Godfather', 'Inception', 'Interstellar', 'Jurassic Park', 'Star Wars', 'The Dark Knight', 'Batman', 'Superman', 'Iron Man', 'Avengers', 'Spider-Man', 'Gladiator', 'Rocky', 'Rambo', 'Terminator', 'Back to the Future', 'Jaws', 'Alien', 'Predator', 'Toy Story', 'Finding Nemo', 'Up', 'The Lion King', 'Aladdin', 'Frozen', 'Shrek', 'Harry Potter', 'Lord of the Rings', 'Hobbit', 'Pirates of the Caribbean', 'Mission Impossible', 'Fast and Furious', 'John Wick', 'La La Land', 'Whiplash'],
      es: ['Titanic', 'Avatar', 'Matrix', 'Pulp Fiction', 'Forrest Gump', 'El Padrino', 'Origen', 'Interestelar', 'Parque Jurásico', 'La Guerra de las Galaxias', 'El Caballero Oscuro', 'Batman', 'Superman', 'Iron Man', 'Vengadores', 'Spider-Man', 'Gladiador', 'Rocky', 'Rambo', 'Terminator', 'Regreso al Futuro', 'Tiburón', 'Alien', 'Depredador', 'Toy Story', 'Buscando a Nemo', 'Up', 'El Rey León', 'Aladdín', 'Frozen', 'Shrek', 'Harry Potter', 'El Señor de los Anillos', 'El Hobbit', 'Piratas del Caribe', 'Misión Imposible', 'Rápidos y Furiosos', 'John Wick', 'La La Land', 'Whiplash'],
      fr: ['Titanic', 'Avatar', 'Matrix', 'Pulp Fiction', 'Forrest Gump', 'Le Parrain', 'Inception', 'Interstellar', 'Jurassic Park', 'Star Wars', 'The Dark Knight', 'Batman', 'Superman', 'Iron Man', 'Avengers', 'Spider-Man', 'Gladiator', 'Rocky', 'Rambo', 'Terminator', 'Retour vers le Futur', 'Les Dents de la Mer', 'Alien', 'Predator', 'Toy Story', 'Le Monde de Nemo', 'Là-haut', 'Le Roi Lion', 'Aladdin', 'La Reine des Neiges', 'Shrek', 'Harry Potter', 'Le Seigneur des Anneaux', 'Le Hobbit', 'Pirates des Caraïbes', 'Mission Impossible', 'Fast and Furious', 'John Wick', 'La La Land', 'Whiplash'],
      it: ['Titanic', 'Avatar', 'Matrix', 'Pulp Fiction', 'Forrest Gump', 'Il Padrino', 'Inception', 'Interstellar', 'Jurassic Park', 'Guerre Stellari', 'Il Cavaliere Oscuro', 'Batman', 'Superman', 'Iron Man', 'Avengers', 'Spider-Man', 'Il Gladiatore', 'Rocky', 'Rambo', 'Terminator', 'Ritorno al Futuro', 'Lo Squalo', 'Alien', 'Predator', 'Toy Story', 'Alla Ricerca di Nemo', 'Up', 'Il Re Leone', 'Aladdin', 'Frozen', 'Shrek', 'Harry Potter', 'Il Signore degli Anelli', 'Lo Hobbit', 'Pirati dei Caraibi', 'Mission Impossible', 'Fast and Furious', 'John Wick', 'La La Land', 'Whiplash'],
    },
  },
  {
    key: 'football teams',
    emoji: '⚽',
    words: {
      en: ['Real Madrid', 'Barcelona', 'Atletico Madrid', 'Manchester United', 'Manchester City', 'Liverpool', 'Chelsea', 'Arsenal', 'Tottenham', 'Bayern Munich', 'Borussia Dortmund', 'Juventus', 'AC Milan', 'Inter Milan', 'Napoli', 'PSG', 'Marseille', 'Ajax', 'PSV', 'Benfica', 'Porto', 'Boca Juniors', 'River Plate', 'Racing', 'Independiente', 'San Lorenzo', 'Flamengo', 'Palmeiras', 'Corinthians', 'Santos', 'Gremio', 'Atletico Mineiro', 'Sao Paulo', 'America', 'Chivas', 'Monterrey', 'Tigres', 'LA Galaxy', 'Inter Miami', 'Al Nassr', 'Al Hilal'],
      es: ['Real Madrid', 'Barcelona', 'Atlético Madrid', 'Manchester United', 'Manchester City', 'Liverpool', 'Chelsea', 'Arsenal', 'Tottenham', 'Bayern Múnich', 'Borussia Dortmund', 'Juventus', 'AC Milan', 'Inter de Milán', 'Napoli', 'PSG', 'Marsella', 'Ajax', 'PSV', 'Benfica', 'Porto', 'Boca Juniors', 'River Plate', 'Racing', 'Independiente', 'San Lorenzo', 'Flamengo', 'Palmeiras', 'Corinthians', 'Santos', 'Gremio', 'Atlético Mineiro', 'Sao Paulo', 'América', 'Chivas', 'Monterrey', 'Tigres', 'LA Galaxy', 'Inter Miami', 'Al Nassr', 'Al Hilal'],
      fr: ['Real Madrid', 'Barcelone', 'Atletico Madrid', 'Manchester United', 'Manchester City', 'Liverpool', 'Chelsea', 'Arsenal', 'Tottenham', 'Bayern Munich', 'Borussia Dortmund', 'Juventus', 'AC Milan', 'Inter Milan', 'Naples', 'PSG', 'Marseille', 'Ajax', 'PSV', 'Benfica', 'Porto', 'Boca Juniors', 'River Plate', 'Racing', 'Independiente', 'San Lorenzo', 'Flamengo', 'Palmeiras', 'Corinthians', 'Santos', 'Gremio', 'Atletico Mineiro', 'Sao Paulo', 'America', 'Chivas', 'Monterrey', 'Tigres', 'LA Galaxy', 'Inter Miami', 'Al Nassr', 'Al Hilal'],
      it: ['Real Madrid', 'Barcellona', 'Atletico Madrid', 'Manchester United', 'Manchester City', 'Liverpool', 'Chelsea', 'Arsenal', 'Tottenham', 'Bayern Monaco', 'Borussia Dortmund', 'Juventus', 'Milan', 'Inter', 'Napoli', 'PSG', 'Marsiglia', 'Ajax', 'PSV', 'Benfica', 'Porto', 'Boca Juniors', 'River Plate', 'Racing', 'Independiente', 'San Lorenzo', 'Flamengo', 'Palmeiras', 'Corinthians', 'Santos', 'Gremio', 'Atletico Mineiro', 'Sao Paulo', 'America', 'Chivas', 'Monterrey', 'Tigres', 'LA Galaxy', 'Inter Miami', 'Al Nassr', 'Al Hilal'],
    },
  },
  {
    key: 'football players',
    emoji: '🏃‍♂️',
    words: {
      en: ['Lionel Messi', 'Cristiano Ronaldo', 'Diego Maradona', 'Pelé', 'Neymar', 'Mbappé', 'Haaland', 'Lewandowski', 'Benzema', 'Zidane', 'Ronaldinho', 'Ronaldo Nazario', 'Xavi', 'Iniesta', 'Modric', 'Kroos', 'Salah', 'Mané', 'Vinicius Jr', 'Griezmann', 'Suarez', 'Cavani', 'Di Maria', 'Tevez', 'Aguero', 'Ibrahimovic', 'Buffon', 'Casillas', 'Neuer', 'Beckham', 'Gerrard', 'Lampard', 'Pirlo', 'Del Piero', 'Kaka', 'Roberto Carlos', 'Dani Alves', 'Marcelo', 'Puyol', 'Ramos'],
      es: ['Lionel Messi', 'Cristiano Ronaldo', 'Diego Maradona', 'Pelé', 'Neymar', 'Mbappé', 'Haaland', 'Lewandowski', 'Benzema', 'Zidane', 'Ronaldinho', 'Ronaldo Nazario', 'Xavi', 'Iniesta', 'Modric', 'Kroos', 'Salah', 'Mané', 'Vinicius Jr', 'Griezmann', 'Suárez', 'Cavani', 'Di María', 'Tévez', 'Agüero', 'Ibrahimovic', 'Buffon', 'Casillas', 'Neuer', 'Beckham', 'Gerrard', 'Lampard', 'Pirlo', 'Del Piero', 'Kaká', 'Roberto Carlos', 'Dani Alves', 'Marcelo', 'Puyol', 'Ramos'],
      fr: ['Lionel Messi', 'Cristiano Ronaldo', 'Diego Maradona', 'Pelé', 'Neymar', 'Mbappé', 'Haaland', 'Lewandowski', 'Benzema', 'Zidane', 'Ronaldinho', 'Ronaldo Nazario', 'Xavi', 'Iniesta', 'Modric', 'Kroos', 'Salah', 'Mané', 'Vinicius Jr', 'Griezmann', 'Suarez', 'Cavani', 'Di Maria', 'Tevez', 'Aguero', 'Ibrahimovic', 'Buffon', 'Casillas', 'Neuer', 'Beckham', 'Gerrard', 'Lampard', 'Pirlo', 'Del Piero', 'Kaka', 'Roberto Carlos', 'Dani Alves', 'Marcelo', 'Puyol', 'Ramos'],
      it: ['Lionel Messi', 'Cristiano Ronaldo', 'Diego Maradona', 'Pelé', 'Neymar', 'Mbappé', 'Haaland', 'Lewandowski', 'Benzema', 'Zidane', 'Ronaldinho', 'Ronaldo Nazario', 'Xavi', 'Iniesta', 'Modric', 'Kroos', 'Salah', 'Mané', 'Vinicius Jr', 'Griezmann', 'Suarez', 'Cavani', 'Di Maria', 'Tevez', 'Aguero', 'Ibrahimovic', 'Buffon', 'Casillas', 'Neuer', 'Beckham', 'Gerrard', 'Lampard', 'Pirlo', 'Del Piero', 'Kaka', 'Roberto Carlos', 'Dani Alves', 'Marcelo', 'Puyol', 'Ramos'],
    },
  },
  {
    key: 'famous people',
    emoji: '🌟',
    words: {
      en: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Leonardo da Vinci', 'Michelangelo', 'Napoleon', 'Cleopatra', 'Julius Caesar', 'Alexander the Great', 'Abraham Lincoln', 'George Washington', 'Nelson Mandela', 'Martin Luther King Jr.', 'Barack Obama', 'Donald Trump', 'Joe Biden', 'Elon Musk', 'Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Jeff Bezos', 'Oprah Winfrey', 'Beyoncé', 'Taylor Swift', 'Michael Jackson', 'Elvis Presley', 'Madonna', 'Freddie Mercury', 'Cristiano Ronaldo', 'Lionel Messi', 'Diego Maradona', 'Pelé', 'Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise', 'Will Smith', 'Scarlett Johansson', 'Jennifer Lawrence', 'Keanu Reeves'],
      es: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Leonardo da Vinci', 'Miguel Ángel', 'Napoleón', 'Cleopatra', 'Julio César', 'Alejandro Magno', 'Abraham Lincoln', 'George Washington', 'Nelson Mandela', 'Martin Luther King Jr.', 'Barack Obama', 'Donald Trump', 'Joe Biden', 'Elon Musk', 'Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Jeff Bezos', 'Oprah Winfrey', 'Beyoncé', 'Taylor Swift', 'Michael Jackson', 'Elvis Presley', 'Madonna', 'Freddie Mercury', 'Cristiano Ronaldo', 'Lionel Messi', 'Diego Maradona', 'Pelé', 'Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise', 'Will Smith', 'Scarlett Johansson', 'Jennifer Lawrence', 'Keanu Reeves'],
      fr: ['Albert Einstein', 'Isaac Newton', 'Galilée', 'Léonard de Vinci', 'Michel-Ange', 'Napoléon', 'Cléopâtre', 'Jules César', 'Alexandre le Grand', 'Abraham Lincoln', 'George Washington', 'Nelson Mandela', 'Martin Luther King Jr.', 'Barack Obama', 'Donald Trump', 'Joe Biden', 'Elon Musk', 'Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Jeff Bezos', 'Oprah Winfrey', 'Beyoncé', 'Taylor Swift', 'Michael Jackson', 'Elvis Presley', 'Madonna', 'Freddie Mercury', 'Cristiano Ronaldo', 'Lionel Messi', 'Diego Maradona', 'Pelé', 'Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise', 'Will Smith', 'Scarlett Johansson', 'Jennifer Lawrence', 'Keanu Reeves'],
      it: ['Albert Einstein', 'Isaac Newton', 'Galileo Galilei', 'Leonardo da Vinci', 'Michelangelo', 'Napoleone', 'Cleopatra', 'Giulio Cesare', 'Alessandro Magno', 'Abraham Lincoln', 'George Washington', 'Nelson Mandela', 'Martin Luther King Jr.', 'Barack Obama', 'Donald Trump', 'Joe Biden', 'Elon Musk', 'Steve Jobs', 'Bill Gates', 'Mark Zuckerberg', 'Jeff Bezos', 'Oprah Winfrey', 'Beyoncé', 'Taylor Swift', 'Michael Jackson', 'Elvis Presley', 'Madonna', 'Freddie Mercury', 'Cristiano Ronaldo', 'Lionel Messi', 'Diego Maradona', 'Pelé', 'Brad Pitt', 'Leonardo DiCaprio', 'Johnny Depp', 'Tom Cruise', 'Will Smith', 'Scarlett Johansson', 'Jennifer Lawrence', 'Keanu Reeves'],
    },
  },
];
